name: plot_twist
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter_animate: ^4.5.2
  firebase_auth: ^6.1.2
  font_awesome_flutter: ^10.8.0
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  debounce_throttle: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  appinio_swiper: ^2.1.1
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.4
  package_info_plus: ^9.0.0
  flutter_markdown_plus: ^1.0.3
  card_swiper: ^3.0.1
  flutter_card_swiper: ^7.0.2
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^16.0.4
  flutter_native_splash: ^2.4.6
  in_app_review: ^2.0.10
  google_sign_in: ^7.1.0
  in_app_purchase: ^3.2.3
  share_plus: ^12.0.1
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.5.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/legal/